import Currency from "@/componenets/Currency";
import {} from "react";




function App() {
  return (
    <>
      <Currency/>
    </>
  );
}

export default App;


export const metadata = {
  title: "Currency Convertor",
  description: "Generated by create next app",
};