import Currency from "@/componenets/Currency";
import {} from "react";




function App() {
  return (
    <div className="bg-black h-screen pt-20">
       <Currency/>
    </div>
     
   
  );
}

export default App;


export const metadata = {
  title: "Currency Convertor",
  description: "Generated by create next app",
};